output "cluster_name" { value = aws_eks_cluster.this.name }
output "cluster_endpoint" { value = aws_eks_cluster.this.endpoint }
output "cluster_ca_certificate" { value = aws_eks_cluster.this.certificate_authority[0].data }
output "cluster_version" { value = aws_eks_cluster.this.version }
output "cluster_security_group_id" { value = aws_eks_cluster.this.vpc_config[0].cluster_security_group_id }
output "oidc_provider_arn" { value = aws_iam_openid_connect_provider.cluster.arn }
output "oidc_provider_url" { value = replace(aws_iam_openid_connect_provider.cluster.url, "https://", "") }
output "node_group_name" { value = aws_eks_node_group.main.node_group_name }
output "node_security_group_id" { value = aws_eks_cluster.this.vpc_config[0].cluster_security_group_id }
output "kubectl_config_command" { value = "aws eks update-kubeconfig --region us-east-1 --name ${aws_eks_cluster.this.name}" }
