apiVersion: v1
kind: ServiceAccount
metadata:
  name: tickets-api-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::720472223188:role/lab-it-support-lab-tickets-api-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: files-api-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::720472223188:role/lab-it-support-lab-files-api-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-api-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::720472223188:role/lab-it-support-lab-metrics-api-sa
